//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
)

func main() {
	const size = 22
	img := image.NewNRGBA(image.Rect(0, 0, size, size))
	w := color.NRGBA{255, 255, 255, 255}

	// Solid filled shield with checkmark, defined as pixel rows.
	// Each row: y -> list of x coordinates to fill white.
	set := func(y int, xs ...int) {
		for _, x := range xs {
			img.SetNRGBA(x, y, w)
		}
	}
	span := func(y, x0, x1 int) {
		for x := x0; x <= x1; x++ {
			img.SetNRGBA(x, y, w)
		}
	}

	// Top flat edge (row 2-3)
	span(2, 4, 17)
	span(3, 3, 18)

	// Straight sides (rows 4-9)
	for y := 4; y <= 9; y++ {
		span(y, 3, 5)   // left wall
		span(y, 16, 18) // right wall
	}

	// Taper begins (rows 10-18)
	span(10, 4, 6)
	span(10, 15, 17)
	span(11, 5, 7)
	span(11, 14, 16)
	span(12, 5, 7)
	span(12, 14, 16)
	span(13, 6, 8)
	span(13, 13, 15)
	span(14, 7, 9)
	span(14, 12, 14)
	span(15, 8, 9)
	span(15, 12, 13)
	span(16, 9, 12)
	span(17, 9, 12)
	span(18, 10, 11)
	set(19, 10, 11)

	// Checkmark inside the shield
	set(7, 7)
	set(8, 7, 8)
	set(9, 8, 9, 14)
	set(10, 9, 10, 13, 14)
	set(11, 10, 11, 12, 13)
	set(12, 11, 12)

	// Encode PNG
	var buf bytes.Buffer
	png.Encode(&buf, img)
	data := buf.Bytes()

	os.WriteFile("icon.png", data, 0644)

	// Write Go source
	var src bytes.Buffer
	src.WriteString("package main\n\n")
	src.WriteString("// iconPNG is a 22x22 white-on-transparent shield+checkmark icon for macOS menu bar.\n")
	src.WriteString("// Generated by gen_icon.go — do not edit manually.\n")
	src.WriteString("var iconPNG = []byte{")
	for i, b := range data {
		if i%16 == 0 {
			fmt.Fprintf(&src, "\n\t")
		}
		fmt.Fprintf(&src, "0x%02x, ", b)
	}
	src.WriteString("\n}\n")
	os.WriteFile("icon.go", src.Bytes(), 0644)

	fmt.Printf("Generated icon.png (%d bytes) and icon.go\n", len(data))
}
